development:
  secret_key_base: a_very_simple_secret
  secret_token: a_very_simple_secret
test:
  secret_key_base: a_very_simple_secret
  secret_token: a_very_simple_secret
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || 'replace_me' %>
  secret_token: <%= ENV["SECRET_TOKEN"] || 'replace_me' %>
