source 'https://rubygems.org'

ruby '2.6.3'
gem 'rails', '4.2.10'
gem 'sass-rails', '~> 5.0.3'
gem 'coffee-rails', '~> 4.1.0'
gem 'uglifier', '>= 2.7.1'

gem 'jquery-rails'
gem 'haml'
gem 'protected_attributes'

gem 'omniauth-google-oauth2'
gem 'omniauth-rails_csrf_protection'
gem 'devise'
gem 'omniauth'

group :development, :test do
  #gem 'pg' ,'~> 0.15'
  
  gem 'sqlite3' , '~> 1.3.6'
  gem 'byebug'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'launchy'
  gem 'rspec-rails'
  gem 'pry'
  gem 'pry-byebug'
  gem 'cucumber-rails' 
  gem 'cucumber-rails-training-wheels'
end

group :production do
  gem 'pg' ,'~> 0.21'
  gem 'rails_12factor'  
end

group :test do
  gem 'cucumber-rails', :require => false
  gem 'cucumber-rails-training-wheels'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'launchy'
  #gem 'pg' ,'~> 0.15'
  #gem 'sqlite3' , '~> 1.3.6'
end
